import { writeFileSync, readFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const rootDir = join(__dirname, '..');

// Generate CalVer: YYYY.MDD.HHMM (UTC)
const now = new Date();
const year = now.getUTCFullYear();
const month = now.getUTCMonth() + 1;
const day = now.getUTCDate();
const hour = now.getUTCHours();
const minute = now.getUTCMinutes();

const calver = `${year}.${month * 100 + day}.${hour * 100 + minute}`;

// Update package.json version in-place so npm publish uses CalVer
const pkgPath = join(rootDir, 'package.json');
const pkg = JSON.parse(readFileSync(pkgPath, 'utf-8')) as Record<string, unknown>;
pkg.version = calver;
writeFileSync(pkgPath, JSON.stringify(pkg, null, 2) + '\n');

// Generate build-info.ts
const buildInfo = `// Auto-generated by scripts/generate-build-info.ts — do not edit
export const BUILD_VERSION = '${calver}' as const;
export const BUILD_TIMESTAMP = '${now.toISOString()}' as const;
`;

writeFileSync(join(rootDir, 'src', 'build-info.ts'), buildInfo);
console.warn(`Generated build-info: v${calver} @ ${now.toISOString()}`);
